## Import Dependencies

In [1]:
import gym
from  stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack  #multiple env can ve vectorized.
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env #used for atari 
import os

In [2]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

Looking in indexes: https://download.pytorch.org/whl/cu117


2. TEST AND UNDERSTAND ENVIRONMENT

In [3]:
!pip install atari-py


In [2]:
!python  -m atari_py.import_roms .\ROMS

copying adventure.bin from .\ROMS\Adventure (1980) (Atari, Warren Robinett) (CX2613, CX2613P) (PAL).bin to C:\Users\nikta\anaconda3\lib\site-packages\atari_py\atari_roms\adventure.bin
copying air_raid.bin from .\ROMS\Air Raid (1982) (Men-A-Vision) (PAL) ~.bin to C:\Users\nikta\anaconda3\lib\site-packages\atari_py\atari_roms\air_raid.bin
copying alien.bin from .\ROMS\Alien (1982) (20th Century Fox Video Games, Douglas 'Dallas North' Neubauer) (11006) ~.bin to C:\Users\nikta\anaconda3\lib\site-packages\atari_py\atari_roms\alien.bin
copying amidar.bin from .\ROMS\Amidar (1982) (Parker Brothers, Ed Temple) (PB5310) ~.bin to C:\Users\nikta\anaconda3\lib\site-packages\atari_py\atari_roms\amidar.bin
copying assault.bin from .\ROMS\Assault (AKA Sky Alien) (1983) (Bomb - Onbase) (CA281).bin to C:\Users\nikta\anaconda3\lib\site-packages\atari_py\atari_roms\assault.bin
copying asterix.bin from .\ROMS\Asterix (AKA Taz) (1984) (Atari, Jerome Domurat, Steve Woita) (CX2696).bin to C:\Users\nikta\anac

In [19]:
environment_name = 'Breakout-v4'
env = gym.make(environment_name,render_mode='human')
#env = gym.make(environment_name)

In [25]:
desired_fps = 10
env.metadata['render_fps'] = desired_fps


In [20]:
env.reset()

(array([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        ...,
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],
 
        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]], dtype=uint8),
 {'lives': 5, 'episode_frame_number': 0, 'frame_number': 0})

In [8]:
env.action_space

Discrete(4)

In [9]:
env.observation_space

Box(0, 255, (210, 160, 3), uint8)

In [10]:
#env.reset()
#env.render()

In [11]:
#env.close()

In [21]:
#running the environment, with random actions.

episodes = 1
for episode in range(1,episodes+1):
    obs = env.reset()
    done = False
    score =0 
    
    while not done:
        env.render()
        action = env.action_space.sample()
        obs,reward,done,_,_ = env.step(action)
        score += reward
    print('episode:{} score :{}'.format(episode,score))
#env.close()



episode:1 score :0.0


In [23]:
env.close()

## 3. VECTORISE ENV AND TRAIN MODEL

In [32]:
environment_name = 'Breakout-v0'
env = gym.make(environment_name,render_mode='human')
desired_fps = 10
env.metadata['render_fps'] = desired_fps

#env = gym.make(environment_name)
env= make_atari_env(environment_name,n_envs=4,seed=0) #we are crearing 4 env at a time
env = VecFrameStack(env,n_stack=4)# we are stacking the 4 env at the same place

C:\Users\nikta\anaconda3\lib\site-packages\gym\envs\registration.py:555: UserWarning: WARN: The environment Breakout-v0 is out of date. You should consider upgrading to version `v4`.
  logger.warn(
C:\Users\nikta\anaconda3\lib\site-packages\gymnasium\envs\registration.py:513: DeprecationWarning: WARN: The environment Breakout-v0 is out of date. You should consider upgrading to version `v4`.
  logger.deprecation(


In [33]:

env.reset()


array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0

In [35]:
desired_fps = 10
env.metadata['render_fps'] = desired_fps


In [36]:
env.render()

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=uint8)

In [38]:
log_path = os.path.join('Logs')
model = A2C('CnnPolicy',env,verbose =1,tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [41]:
model.learn(total_timesteps=100000)

Logging to Logs\A2C_3
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 317      |
|    ep_rew_mean        | 2.15     |
| time/                 |          |
|    fps                | 174      |
|    iterations         | 100      |
|    time_elapsed       | 11       |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -0.395   |
|    explained_variance | 0.977    |
|    learning_rate      | 0.0007   |
|    n_updates          | 649      |
|    policy_loss        | -0.00482 |
|    value_loss         | 0.0188   |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 308      |
|    ep_rew_mean        | 2.03     |
| time/                 |          |
|    fps                | 173      |
|    iterations         | 200      |
|    time_elapsed       | 23       |
|    total_timesteps    | 4000     |
| train/        

## 4. Save and Relaod Model

In [45]:
model.save('models/A2C_CNN_break_out_100000')

In [50]:
#del model

In [49]:
model = A2C.load('models/A2C_CNN_break_out_100000.zip',env)

#reloaded the model.

Wrapping the env in a VecTransposeImage.


## 5. Evaluate and Test

In [51]:
env= make_atari_env('Breakout-v0', n_envs=1,seed =0 )
env = VecFrameStack(env,n_stack=4)

C:\Users\nikta\anaconda3\lib\site-packages\gymnasium\envs\registration.py:513: DeprecationWarning: WARN: The environment Breakout-v0 is out of date. You should consider upgrading to version `v4`.
  logger.deprecation(


In [54]:
evaluate_policy(model,env,n_eval_episodes=50,render= True)

(5.84, 2.556247249387273)

In [53]:
env.close()

In [ ]:
# another approach , where we using gyma and atari for env creation.

In [57]:
"""
import gym
#from stable_baselines3.common.envs import AtariWrapper
from stable_baselines3.common.vec_env import VecFrameStack, DummyVecEnv

# Create the Atari environment
environment_name = 'Breakout-v0'
env = gym.make(environment_name)

# Wrap the environment in the AtariWrapper to make it compatible with Stable Baselines3
#env = AtariWrapper(env)

# Wrap the environment in a DummyVecEnv
env = DummyVecEnv([lambda: env])

# Initialize VecFrameStack to handle the stacking of frames
env = VecFrameStack(env, n_stack=4)  # Stack 4 frames

# Run the environment with rendering
obs = env.reset()
while True:
    action, _ = model.predict(obs)  # Replace 'model' with your RL model
    obs, _, done, _ = env.step(action)
    env.render(mode='human')  # Render in 'human' mode for human-friendly visualization
    if done:
        break

# Close the rendering window when done
env.close()
"""

"\nimport gym\n#from stable_baselines3.common.envs import AtariWrapper\nfrom stable_baselines3.common.vec_env import VecFrameStack, DummyVecEnv\n\n# Create the Atari environment\nenvironment_name = 'Breakout-v0'\nenv = gym.make(environment_name)\n\n# Wrap the environment in the AtariWrapper to make it compatible with Stable Baselines3\n#env = AtariWrapper(env)\n\n# Wrap the environment in a DummyVecEnv\nenv = DummyVecEnv([lambda: env])\n\n# Initialize VecFrameStack to handle the stacking of frames\nenv = VecFrameStack(env, n_stack=4)  # Stack 4 frames\n\n# Run the environment with rendering\nobs = env.reset()\nwhile True:\n    action, _ = model.predict(obs)  # Replace 'model' with your RL model\n    obs, _, done, _ = env.step(action)\n    env.render(mode='human')  # Render in 'human' mode for human-friendly visualization\n    if done:\n        break\n\n# Close the rendering window when done\nenv.close()\n"